version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      gatsby:
        patterns:
          - "gatsby"
          - "gatsby-*"
      dev-dependencies:
        dependency-type: development
    commit-message:
      prefix: chore
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
