version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            gem install percy-cli

      - run:
          name: Run tests
          command: |
            npx gatsby build
            percy snapshot public
